[en]
  languageName = "English"
  weight = 2

[fr]
  languageName = "Français"
  weight = 1
  [fr.params]
    dateFormat = "02/01/2006"
    description = "Site de la communauté francophone de darktable"
    keywords = "darktable, photo, raw"

[zh-cn]
  languageName = "简体中文"
  weight = 4
  [zh-cn.params]
    dateFormat = "2006-01-02"
    description = "一个快速、响应式和功能丰富的 Hugo 博客主题"
    keywords = "Hugo, Bootstrap, 博客主题"
    [zh-cn.params.archive]
      dateFormat = "01-02"

[zh-tw]
  languageName = "繁體中文"
  weight = 3
  [zh-tw.params]
    dateFormat = "2006-01-02"
    description = "一個快速、響應式和功能豐富的 Hugo 博客主題"
    keywords = "Hugo, Bootstrap, 博客主題"
    [zh-tw.params.archive]
      dateFormat = "01-02"
